config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :users, only: %I[index show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :projects
  get '/external', to: 'projects#external'

  resources :groups

  resources :logs, only: %i[new create]

  authenticated :user do
    root 'home#home', as: :authenticated_root
  end

  unauthenticated :user do
    root 'home#landing', as: :unauthenticated_root
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :logs, dependent: :destroy
  has_many :projects, through: :logs
  has_one_attached :group_image
  scope :with_attached_group_image, -> { includes(group_image_attachment: :blob) }

  paginates_per 5
  validates :name, presence: true, length: { minimum: 6 }, uniqueness: { case_sensitive: false }
  validates :group_image, presence: { message: 'Need a picture!' }
end

app/controllers/group_controller.rb
class GroupController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = Group.all.order('name ASC')
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = current_user.groups.build
  end

  def create
    @group = current_user.groups.build(groups_param)
    if @group.save
      flash[:success] = 'Group created!'
      redirect_to groups_path
    else
      render 'new'
    end
  end

    private

  def groups_param
    params.require(:group).permit(:name)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: %i[edit update show destroy]

  def index
    @groups = Group.all.order('name ASC').with_attached_group_image.page params[:page]
  end

  def show
    session[:current_group] = @group.id
  end

  def new
    @group = current_user.groups.build
  end

  def create
    @group = current_user.groups.build(groups_param)
    if @group.save
      flash[:success] = 'Group created!'
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @group.update(groups_param)
      flash[:success] = 'Article was successfully updated'
      redirect_to group_path(@group)
    else
      render 'edit'
    end
  end

  def destroy
    @group.destroy
    flash[:danger] = 'Article was successfully deleted'
    redirect_to groups_path
  end

  private

  def groups_param
    params.require(:group).permit(:name, :group_image)
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/helpers/group_helper.rb
module GroupHelper

  def display_groups(groups)
    groups.each do |group|
      concat(
        content_tag(:div, nil, class: 'border-0 border-bottom bg-primary') do
          content_tag(:div, nil, class: 'row g-0 mx-1') do
            content_tag(:div, nil, class: 'col-4') do
              content_tag(:img, nil,
                          src: 'https://robbreport.com/wp-content/uploads/2018/04/gordon-ramsay-1-e1523056498302.jpg?w=1008',
                          class: 'pt-3 project-img')
            end +
              content_tag(:div, nil, class: 'col-8') do
                content_tag(:div, nil, class: 'card-body ms-2 px-1') do
                  content_tag(:div, nil, class: 'd-flex justify-content-betw  een') do
                    link_to(group_path(group)) do
                      content_tag(:p, group.name, class: 'card-text fs-group text-white')
                    end
                  end +
                    content_tag(:p, nil, class: 'card-text') do
                      content_tag(:small, group.created_at, class: 'text-white fw-lighter fz-creation mb-1')
                    end
                end
              end
          end
        end
      )
    end
  end

end

app/helpers/groups_helper.rb
# rubocop:disable all

# frozen_string_literal: true

module GroupsHelper
  def display_groups(groups)
    groups.each do |group|
      concat(
        content_tag(:div, nil, class: 'border-0 border-bottom bg-primary pb-3') do
          content_tag(:div, nil, class: 'row g-0 mx-1') do
            content_tag(:div, nil, class: 'col-4') do
              image_tag group.group_image.variant(resize_and_pad: [120, 90]), class: 'pt-3'
            end +
              content_tag(:div, nil, class: 'col-8') do
                content_tag(:div, nil, class: 'card-body ms-2') do
                  content_tag(:div, nil, class: 'd-flex justify-content-between') do
                    link_to(group_path(group)) do
                      content_tag(:p, group.name, class: 'card-text fs-groups text-white proxima-bold')
                    end
                  end +
                    content_tag(:p, nil, class: 'card-text pt-2') do
                      content_tag(:small,
                                  "Created #{time_ago_in_words(group.created_at)} ago",
                                  class: 'text-white fw-lighter fz-creation proxima-light')
                    end
                end
              end +
              content_tag(:div, nil, class: 'd-flex justify-content-between px-1 pt-2') do
                content_tag(:span, nil) do
                  link_to 'Edit Group', edit_group_path(group), class: 'btn btn-sm btn-outline-warning fs-groups text-white proxima-bold mb-0 text-decoration-none'
                end +
                  content_tag(:span, nil) do
                    link_to 'Delete Group', group_path(group), method: :delete, data: {:confirm => "Delete Group?" }, class: 'btn btn-sm btn-outline-danger fs-groups text-white proxima-bold mb-0 text-decoration-none'
                  end
              end
          end
        end
      )
    end
  end
end
# rubocop:enable all

app/views/groups/edit.html.erb
<%= render 'shared/navbar' %>

<div class="px-2 mt-2">
  <%= simple_form_for @group do |f| %>
    <%= f.input :name, required: true,
                autofocus: true,
                input_html: { autocomplete: "name", class: 'mb-2 proxima-light' },
                label: false,
                placeholder: 'Group\'s name' %>

    <%= f.file_field :group_image, class: 'form-control proxima-light' %>

    <div class="fixed-bottom">
      <div class="d-grid gap-2 p-3 bg-primary text-white">
        <%= f.button :submit, "Create Group", class: 'btn btn-outline-light py-2 w-100 proxima-light' %>
      </div>
    </div>
  <% end %>
</div>

app/views/groups/index.html.erb
<%= render 'shared/navbar' %>

<div class="text-center fs-2 py-1 bg-primary text-light ">
  <p class="mb-0 proxima-bold">
    All Groups
  </p>
</div>

<div class="bg-primary pt-3 pb-5" style="height: 100vh">
  <ul class="list-group list-group-flush px-3 bg-primary pb-feed mb-4">
    <% display_groups(@groups) %>
    <div class="pt-3">
      <%= paginate @groups %>
    </div>
  </ul>
</div>

<div class="fixed-bottom">
  <div class="d-grid gap-2 p-3 bg-success text-white proxima-light">
    <%= link_to 'New Group', new_group_path, class: 'btn btn-outline-light py-2 w-100 proxima-light' %>
  </div>
</div>

app/views/groups/new.html.erb
<%= render 'shared/navbar' %>

<div class="px-2 mt-2">
  <%= simple_form_for @group do |f| %>
    <%= f.input :name, required: true,
                autofocus: true,
                input_html: { autocomplete: "name", class: 'mb-2 proxima-light' },
                label: false,
                placeholder: 'Group\'s name' %>

    <%= f.file_field :group_image, class: 'form-control proxima-light text-muted' %>

    <div class="fixed-bottom">
      <div class="d-grid gap-2 p-3 bg-primary text-white">
        <%= f.button :submit, "Create Group", class: 'btn btn-outline-light py-2 w-100 proxima-light' %>
      </div>
    </div>
  <% end %>
</div>

app/views/groups/show.html.erb
<%= render 'shared/navbar' %>

<div class="text-center fs-2 py-1 bg-primary text-light">
  <p class="mb-0 proxima-bold">
    <%= @group.name.capitalize %> Projects
  </p>
</div>

<div class="mb-feed">
  <% display_group_projects(@group.projects) %>
</div>

<div class="fixed-bottom">
  <div class="d-grid gap-2 p-3 bg-success text-white proxima-light text-muted">
    <%= link_to 'Add Project', new_log_path, class: 'btn btn-outline-light py-2 w-100 proxima-light' %>
  </div>
</div>