config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :users, only: %I[index show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :projects
  get '/external', to: 'projects#external'

  resources :groups

  resources :logs, only: %i[new create]

  authenticated :user do
    root 'home#home', as: :authenticated_root
  end

  unauthenticated :user do
    root 'home#landing', as: :unauthenticated_root
  end
end

app/views/shared/_alerts.html.erb
<% flash.each do |name, msg| %>
  <%= flash_messages(name, msg) %>
<% end %>

app/views/shared/_log.html.erb
<div class="px-2 mt-2">
  <%= simple_form_for object do |f| %>
    <%= f.input :project_id,
                required: true,
                collection: @project_options,
                prompt: "Select your project",
                autofocus: true,
                input_html: { autocomplete: "name", class: 'mb-2 proxima-light' },
                label: false,
                selected: @project_options.first %>

    <div class="fixed-bottom">
      <div class="d-grid gap-2 p-3 bg-primary text-white">
        <%= f.button :submit, "Add Project", class: 'btn btn-outline-light py-2 w-100 proxima-light' %>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="p-3 pb-0 bg-primary text-white">
  <nav class="navbar navbar-expand-lg navbar navbar-dark bg-primary">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to request.referer.present? ? request.referer : authenticated_root_path do %>
        <i class="fas fa-angle-double-left text-white fs-1"></i>
      <% end %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item proxima-bold">
            <%= user_name %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle proxima-bold" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Menu
            </a>
            <ul class="dropdown-menu proxima-bold" aria-labelledby="navbarDropdown">
              <%= navbar_dropdown %>
            </ul>
          </li>
          <% if signed_in? %>
            <li class="nav-item proxima-bold">
              <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'nav-link proxima-bold' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</div>