config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :users, only: %I[index show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :projects
  get '/external', to: 'projects#external'

  resources :groups

  resources :logs, only: %i[new create]

  authenticated :user do
    root 'home#home', as: :authenticated_root
  end

  unauthenticated :user do
    root 'home#landing', as: :unauthenticated_root
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: ['landing']
  def home; end

  def landing; end
end

app/helpers/home_helper.rb
# rubocop:disable all

# frozen_string_literal: true

module HomeHelper
  def profile_picture
    content_tag(:div, nil, class: 'd-flex pt-3 justify-content-center') do
      image_tag current_user.picture.variant(resize_and_pad: [200, 200]), class: 'rounded-circle mx-auto'
    end
  end
end
# rubocop:enable all

app/views/home/home.html.erb
<%= render 'shared/navbar' %>

<div class="bg-primary" style="height: 100vh">
  <%= profile_picture %>>

  <h3 class="py-3 text-center text-white proxima-bold">
    <%= current_user.name.capitalize %>
  </h3>


  <ul class="list-group list-group-flush px-4 proxima-bold">
    <li class="list-group-item bg-primary border-white">
      <div class="d-flex justify-content-start align-items-center text-white fs-menu py-1">
        <i class="fas fa-user pe-4"></i>
        <%= link_to 'All My Projects', projects_path, class: 'text-white text-decoration-none' %>
      </div>
    </li>

    <li class="list-group-item bg-primary border-white proxima-bold">
      <div class="d-flex justify-content-start align-items-center text-white fs-menu py-1">
        <i class="fas fa-users-slash pe-3"></i>
        <%= link_to 'My External Projects', external_path, class: 'text-white text-decoration-none' %>
      </div>
    </li>

    <li class="list-group-item bg-primary border-white proxima-bold">
      <div class="d-flex justify-content-start align-items-center text-white fs-menu py-1">
        <i class="fas fa-users pe-3"></i>
        <%= link_to 'All Groups', groups_path, class: 'text-white text-decoration-none' %>
      </div>
    </li>

    <li class="list-group-item bg-primary border-white proxima-bold">
      <div class="d-flex justify-content-start align-items-center text-white fs-menu py-1">
        <i class="fas fa-user pe-4"></i>
        <%= link_to 'Other Users', users_path, class: 'text-white text-decoration-none' %>
      </div>
    </li>
  </ul>
</div>

app/views/home/landing.html.erb
<div class="d-flex justify-content-center align-items-center proxima-bold" style="height: 28rem;">
  <h1>Hell's Kitchen</h1>
</div>

<div class="d-grid gap-2 fixed-bottom my-3 px-3">
  <%= link_to 'LOG IN', new_user_session_path, class: 'btn btn-primary proxima-light' %>

  <%= link_to 'SIGN UP', new_user_registration_path, class: 'text-center text-decoration-none proxima-light' %>
</div>